/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.CarType;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author devinajaiswal
 */
public class CreateCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form createcarPanel
     */
    private CarType car;
    public static String imPath;


   
    
    
    public CreateCarPanel(CarType car) {
        this.car=car;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        makeTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        extColorTextField = new javax.swing.JTextField();
        intColorTextField = new javax.swing.JTextField();
        engineTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        transmissionTextField = new javax.swing.JTextField();
        cityMPGTextField = new javax.swing.JTextField();
        highwayMPGTextField = new javax.swing.JTextField();
        cylinderTextField = new javax.swing.JTextField();
        grossVehicleWtTextField = new javax.swing.JTextField();
        fuelCapacityTextField = new javax.swing.JTextField();
        sunroofAvailTextField = new javax.swing.JTextField();
        fuelSourceTextField = new javax.swing.JTextField();
        warrantyTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        uploadImageButton = new javax.swing.JButton();
        cardetailsEntered = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Enter your car details");

        jLabel2.setText("Make");

        jLabel3.setText("Model");

        jLabel4.setText("Exterior Color");

        jLabel5.setText("Interior Color");

        jLabel6.setText("Fuel source");

        jLabel7.setText("Engine");

        jLabel8.setText("Price");

        jLabel9.setText("Transmission");

        jLabel10.setText("City MPG");

        jLabel11.setText("Highway MPG");

        jLabel12.setText("Cylinder");

        jLabel13.setText("Gross Vehicle weight");

        jLabel14.setText("Fuel Capacity");

        jLabel15.setText("Warranty");

        jLabel16.setText("Sunroof Availability ");

        makeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTextFieldActionPerformed(evt);
            }
        });

        highwayMPGTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highwayMPGTextFieldActionPerformed(evt);
            }
        });

        fuelCapacityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelCapacityTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("Upload Image");

        uploadImageButton.setText("Browse");
        uploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageButtonActionPerformed(evt);
            }
        });

        cardetailsEntered.setText("Enter");
        cardetailsEntered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardetailsEnteredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadImageButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(makeTextField)
                        .addComponent(modelTextField)
                        .addComponent(extColorTextField)
                        .addComponent(intColorTextField)
                        .addComponent(engineTextField)
                        .addComponent(priceTextField)
                        .addComponent(transmissionTextField)
                        .addComponent(cityMPGTextField)
                        .addComponent(highwayMPGTextField)
                        .addComponent(cylinderTextField)
                        .addComponent(grossVehicleWtTextField)
                        .addComponent(fuelCapacityTextField)
                        .addComponent(sunroofAvailTextField)
                        .addComponent(warrantyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addComponent(fuelSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cardetailsEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(extColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(intColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(engineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(transmissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cityMPGTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(highwayMPGTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grossVehicleWtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fuelCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sunroofAvailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fuelSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(warrantyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(uploadImageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(cardetailsEntered)
                .addGap(209, 209, 209))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeTextFieldActionPerformed

    private void highwayMPGTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highwayMPGTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highwayMPGTextFieldActionPerformed

    private void uploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageButtonActionPerformed
        // TODO add your handling code here:
        
        // to create a working browse button
        JFileChooser fChooser=new JFileChooser();
       fChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
       FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Images", "jpg","gif","png","jpeg");
       fChooser.addChoosableFileFilter(filter);
       int resultPath= fChooser.showSaveDialog(null);
       if(resultPath== JFileChooser.APPROVE_OPTION){
           File sfile=fChooser.getSelectedFile();
           imPath=sfile.getAbsolutePath(); // Copying image path in a static variable imPath
           JOptionPane.showMessageDialog(null,"Image is Selected successfully");
   
       }
       else if (resultPath== JFileChooser.CANCEL_OPTION){
           JOptionPane.showMessageDialog(null,"No File selected!");
           
       }
    }//GEN-LAST:event_uploadImageButtonActionPerformed

    private void fuelCapacityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelCapacityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelCapacityTextFieldActionPerformed

    private void cardetailsEnteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardetailsEnteredActionPerformed
        // TODO add your handling code here:
        // Binding the user input to the car object
        car.setMake(makeTextField.getText());
        car.setModel(modelTextField.getText());
        car.setExtColor(extColorTextField.getText());
        car.setIntColor(intColorTextField.getText());
        car.setPrice(priceTextField.getText());
        car.setTransmission(transmissionTextField.getText());
        car.setCityMpg(cityMPGTextField.getText());
        car.setHighwayMpg(highwayMPGTextField.getText());
        car.setCylinder(cylinderTextField.getText());
        car.setGrossvehiclewt(grossVehicleWtTextField.getText());
        car.setFuelCapacity(fuelCapacityTextField.getText());
        car.setSunroofAvail(sunroofAvailTextField.getText());
        car.setFuelSource(fuelSourceTextField.getText());
        car.setWarranty(warrantyTextField.getText());
        car.setEngine(engineTextField.getText());
        

        JOptionPane.showMessageDialog(null,"Car details entered successfully!");
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_cardetailsEnteredActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardetailsEntered;
    private javax.swing.JTextField cityMPGTextField;
    private javax.swing.JTextField cylinderTextField;
    private javax.swing.JTextField engineTextField;
    private javax.swing.JTextField extColorTextField;
    private javax.swing.JTextField fuelCapacityTextField;
    private javax.swing.JTextField fuelSourceTextField;
    private javax.swing.JTextField grossVehicleWtTextField;
    private javax.swing.JTextField highwayMPGTextField;
    private javax.swing.JTextField intColorTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JTextField makeTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField sunroofAvailTextField;
    private javax.swing.JTextField transmissionTextField;
    private javax.swing.JButton uploadImageButton;
    private javax.swing.JTextField warrantyTextField;
    // End of variables declaration//GEN-END:variables
}
