/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarType;

/**
 *
 * @author devinajaiswal
 */
public class FrameDesign extends javax.swing.JFrame {

    /**
     * Creates new form FrameDesign
     */
    private CarType car;

    public FrameDesign() {
        initComponents();
        car = new CarType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        createPanel = new javax.swing.JPanel();
        createCar = new javax.swing.JButton();
        viewCar = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1700, 1700));
        setSize(new java.awt.Dimension(1080, 1080));

        createCar.setText("Enter car details");
        createCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCarActionPerformed(evt);
            }
        });

        viewCar.setText("View car details");
        viewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createCar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewCar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(createCar)
                .addGap(200, 200, 200)
                .addComponent(viewCar)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        splitPanel.setLeftComponent(createPanel);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(displayPanel);

        getContentPane().add(splitPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCarActionPerformed
        // TODO add your handling code here:

        CreateCarPanel createCarPanel = new CreateCarPanel(car);
        splitPanel.setRightComponent(createCarPanel);


    }//GEN-LAST:event_createCarActionPerformed

    private void viewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCarActionPerformed
        // TODO add your handling code here:
        ViewCarPanel viewCarPanel= new ViewCarPanel(car);
       splitPanel.setRightComponent(viewCarPanel);
    }//GEN-LAST:event_viewCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCar;
    private javax.swing.JPanel createPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JButton viewCar;
    // End of variables declaration//GEN-END:variables
}
