/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Business.Product;
import Business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author devinajaiswal
 */
public class CreateProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateProductJPanel
     */
    private JPanel userProcessContainer;
   private ProductCatalog productList;
    CreateProductJPanel(JPanel userProcessContainer, ProductCatalog productList) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    initComponents();
    this.productList=productList;
    this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        routingNumberJLabel = new javax.swing.JLabel();
        accountNumberJLabel = new javax.swing.JLabel();
        bankNameJLabel = new javax.swing.JLabel();
        balanceJLabel = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        availNumTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        headerJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        headerJLabel.setText("Enter the Product Details");

        routingNumberJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        routingNumberJLabel.setText("Product Name");
        routingNumberJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        accountNumberJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountNumberJLabel.setText("Price");
        accountNumberJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bankNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bankNameJLabel.setText("Available Number");
        bankNameJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        balanceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        balanceJLabel.setText("Description");
        balanceJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(171, 171, 171)
                        .addComponent(headerJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routingNumberJLabel)
                            .addComponent(accountNumberJLabel)
                            .addComponent(bankNameJLabel)
                            .addComponent(balanceJLabel))
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descriptionTextField)
                            .addComponent(availNumTextField)
                            .addComponent(priceTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(btnSave)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerJLabel)
                    .addComponent(btnBack))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingNumberJLabel)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberJLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnSave)
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here
       
        Product product= productList.addProduct();
        try{
            if(productNameTextField.getText()=="" || productNameTextField.getText()==null )
            JOptionPane.showMessageDialog(null, "Please enter the product name!");
                 
        }
        catch(NullPointerException e){
         JOptionPane.showMessageDialog(null, "Please enter the product name!"); 
        }
        finally
{
         JOptionPane.showMessageDialog(null, "Please enter the product name!"); 
        } 
        
        try{
        Double.parseDouble(priceTextField.getText());
           
        }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null, "Please enter the number value for price!");
        }
         try{
      Integer.parseInt(availNumTextField.getText());
           
        }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null, "Please enter the number value for available number!");
        }

try{
         if(descriptionTextField.getText()=="" || descriptionTextField.getText()==null )
            JOptionPane.showMessageDialog(null, "Please enter the product description");
          
                 
        }
        catch(NullPointerException e){
         JOptionPane.showMessageDialog(null, "Please enter the product description!"); 
        } 
       
         
        try{
         int availNum= Integer.parseInt(availNumTextField.getText());
        
        
        double price= Double.parseDouble(priceTextField.getText());
        
        String description= descriptionTextField.getText();
        
        String productName = productNameTextField.getText();
       
       
        product.setDescription(description);
        product.setAvailNum(availNum);
       product.setName(productName); 
         productNameTextField.setText("");
        availNumTextField.setText("");
        priceTextField.setText("");
        descriptionTextField.setText("");
        
        JOptionPane.showMessageDialog(null, "Product successfully created!");}
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Product cannot be created successfully! Please enter correct values");
        }
    
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberJLabel;
    private javax.swing.JTextField availNumTextField;
    private javax.swing.JLabel balanceJLabel;
    private javax.swing.JLabel bankNameJLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JLabel routingNumberJLabel;
    // End of variables declaration//GEN-END:variables
}
