/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author devinajaiswal
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductJPanel
     */
    private JPanel userProcessContainer;
    private Product product;
    ViewProductJPanel(JPanel userProcessContainer,Product product) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.product=product;
        populateProductDetails();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
    }

    private void populateProductDetails(){
          productNameTextField.setText((product.getName()));
    priceTextField.setText(product.getPrice().toString());
    descriptionTextField.setText(product.getDescription());
     availNumTextField.setText(product.getAvailNum().toString());
        
    }
  
     
    
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        routingNumberJLabel = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        accountNumberJLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        availNumTextField = new javax.swing.JTextField();

        headerJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        headerJLabel.setText("Product Details");

        routingNumberJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        routingNumberJLabel.setText("Product Name");
        routingNumberJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        productNameTextField.setEnabled(false);

        accountNumberJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountNumberJLabel.setText("Price");
        accountNumberJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        priceTextField.setEnabled(false);
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        Description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Description.setText("Description");
        Description.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        descriptionTextField.setEnabled(false);

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setText("Available Number");

        availNumTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(217, 217, 217)
                        .addComponent(headerJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(routingNumberJLabel)
                                .addComponent(accountNumberJLabel)
                                .addComponent(Description)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(priceTextField)
                                    .addComponent(descriptionTextField)
                                    .addComponent(availNumTextField))))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(headerJLabel))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingNumberJLabel)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberJLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(availNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
      
        
        availNumTextField.setEnabled(true);
        productNameTextField.setEnabled(true);
        priceTextField.setEnabled(true);
        descriptionTextField.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
        
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
           try{
        try{
          productNameTextField.getText().charAt(0);
          
                 
        }
        catch(NullPointerException e){
         JOptionPane.showMessageDialog(null, "Please enter the product name!"); 
        } 
       catch(StringIndexOutOfBoundsException e){
         JOptionPane.showMessageDialog(null, "Please enter the product name!"); 
        } 
        finally
{
         JOptionPane.showMessageDialog(null, "Please enter the product name!"); 
        } 
        
        try{
        Double.parseDouble(priceTextField.getText());
           
        }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null, "Please enter the number value for price!");
        }
         try{
      Integer.parseInt(availNumTextField.getText());
           
        }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null, "Please enter the number value for available number!");
        }

try{
         descriptionTextField.getText().charAt(0);
          
                 
        }
        catch(NullPointerException e){
         JOptionPane.showMessageDialog(null, "Please enter the product description!"); 
        } 
       catch(StringIndexOutOfBoundsException e){
         JOptionPane.showMessageDialog(null, "Please enter the product description!"); 
        } 
        finally
{
         JOptionPane.showMessageDialog(null, "Please enter the product description!"); 
        } 
         
        product.setName(productNameTextField.getText());
        product.setPrice(Double.parseDouble(priceTextField.getText()));
        product.setDescription(descriptionTextField.getText());
        product.setAvailNum(Integer.parseInt(availNumTextField.getText()));
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Product updated successfully!");}
           catch(Exception e){
           
              JOptionPane.showMessageDialog(null, "Product updated successfully!");
           
           }
           
    }//GEN-LAST:event_btnSaveActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel accountNumberJLabel;
    private javax.swing.JTextField availNumTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JLabel routingNumberJLabel;
    // End of variables declaration//GEN-END:variables
}
