/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Interface.ViewJPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author devinajaiswal
 */
public class AbnormalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbnormalJPanel
     */
    private VitalSignHistory vitalSignHistory;
    private double maxBp;
    private double minBp;
    public AbnormalJPanel(VitalSignHistory vitalSignHistory, double maxBp, double minBp) {
        initComponents();
        this.vitalSignHistory=vitalSignHistory;
        this.maxBp=maxBp;
        this.minBp=minBp;
        
        populateTable();
    }
    
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchTbl = new javax.swing.JTable();
        viewDetailBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        temperatureLabel = new javax.swing.JLabel();
        temperatureTextField = new javax.swing.JTextField();
        bloodPressureLabel = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        pulseLabel = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();

        searchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchTbl);

        viewDetailBtn.setText("View");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        temperatureLabel.setText("Temperature");

        temperatureTextField.setEnabled(false);

        bloodPressureLabel.setText("Blood Pressure");

        bloodPressureTextField.setEnabled(false);

        pulseLabel.setText("Pulse");

        pulseTextField.setEnabled(false);

        dateLabel.setText("Date");

        dateTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pulseLabel)
                                        .addComponent(dateLabel)
                                        .addComponent(bloodPressureLabel)
                                        .addComponent(temperatureLabel))
                                    .addGap(155, 155, 155)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pulseTextField)
                                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bloodPressureTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                            .addComponent(temperatureTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(424, 424, 424)
                                    .addComponent(viewDetailBtn)
                                    .addGap(48, 48, 48)
                                    .addComponent(DeleteBtn)))
                            .addGap(33, 33, 33)))
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewDetailBtn)
                        .addComponent(DeleteBtn))
                    .addGap(117, 117, 117)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(temperatureLabel)
                        .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bloodPressureLabel)
                        .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pulseLabel)
                        .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = searchTbl.getSelectedRow();

        if(selectedRow >=0)
        {
            VitalSigns vs= (VitalSigns)searchTbl.getValueAt(selectedRow, 0);
            bloodPressureTextField.setText(String.valueOf(vs.getBloodpressure()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            temperatureTextField.setText(String.valueOf(vs.getTemperature()));
            dateTextField.setText(vs.getDate());
        }

        else
        JOptionPane.showMessageDialog(null,"Please select any row");
    }//GEN-LAST:event_viewDetailBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = searchTbl.getSelectedRow();

        if(selectedRow >=0)
        {
            VitalSigns vs= (VitalSigns)searchTbl.getValueAt(selectedRow, 0);
            vitalSignHistory.deleteVitals(vs);
            JOptionPane.showMessageDialog(null,"Vital Sign deleted successfully!");
            populateTable();
        }

        else
        JOptionPane.showMessageDialog(null,"Please select any row");

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void populateTable(){
        DefaultTableModel dtm= (DefaultTableModel) searchTbl.getModel();
        dtm.setRowCount(0);
        for (VitalSigns vs: vitalSignHistory.getAbnormalList(maxBp, minBp)){
            
             Object row[]= new Object[2];
             row[0]=vs;
             row[1]=vs.getBloodpressure();
             dtm.addRow(row);
             
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulseLabel;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JTable searchTbl;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JTextField temperatureTextField;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
