/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarDirectory;
import java.awt.CardLayout;
import java.awt.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author devinajaiswal
 */
public class ManageCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountPanel
     */
    private JPanel userProcessContainer;
    private CarDirectory carList;
    public ManageCarJPanel(JPanel userProcessContainer, CarDirectory carList) {
        initComponents();
       this.userProcessContainer=userProcessContainer;
        this.carList=carList;
    
    populateTable();
    }

    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel();
        dtm.setRowCount(0);
  
        for(Car car: carList.getCarList()){
            Object[] row=new Object[6];
            row[0]=car;
            row[1]=car.getSerialNo();
            row[2]=car.getModelNo();
            row[3]=car.getAvailableCity();
            row[4]=car.getDistance();
            row[5]=car.getManufacturedYear();
           
            dtm.addRow(row);
      
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        carJTable = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        searchDropDown = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExpMaintenanceCert = new javax.swing.JButton();
        btnFirstCarAvailable = new javax.swing.JButton();
        btnAvailabilityOfCars = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAllManufacturers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search1TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        search2TextField = new javax.swing.JTextField();
        btnSearch2Filter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        srchSerialNoJTextField = new javax.swing.JTextField();
        btnSrchSerialNumber = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        carJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Make", "Serial Number", "Model Number", "City", "Distance", "Manufactured Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carJTable);
        if (carJTable.getColumnModel().getColumnCount() > 0) {
            carJTable.getColumnModel().getColumn(0).setResizable(false);
            carJTable.getColumnModel().getColumn(1).setResizable(false);
            carJTable.getColumnModel().getColumn(2).setResizable(false);
            carJTable.getColumnModel().getColumn(3).setResizable(false);
            carJTable.getColumnModel().getColumn(4).setResizable(false);
            carJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        btnDetails.setText("View Details ");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make", "Model Number", "City", "Manufactured Year" }));
        searchDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDropDownActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Cars with expired Maintenance Cetificate ");

        btnExpMaintenanceCert.setText("Find");
        btnExpMaintenanceCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpMaintenanceCertActionPerformed(evt);
            }
        });

        btnFirstCarAvailable.setText("Find the first available car");
        btnFirstCarAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstCarAvailableActionPerformed(evt);
            }
        });

        btnAvailabilityOfCars.setText("Availability of Cars");
        btnAvailabilityOfCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailabilityOfCarsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Car List");

        btnAllManufacturers.setText("List all the car manufacturers");
        btnAllManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllManufacturersActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Filter cars according to make and city ");

        jLabel4.setText("Enter the make");

        search1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1TextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter the city");

        btnSearch2Filter.setText("Search");
        btnSearch2Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2FilterActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Search car according to Serial Number");

        jLabel7.setText("Enter the serial number");

        btnSrchSerialNumber.setText("Search");
        btnSrchSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchSerialNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack)
                        .addGap(310, 310, 310)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(search2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(search1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnSearch2Filter))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(srchSerialNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSrchSerialNumber)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFirstCarAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExpMaintenanceCert, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAvailabilityOfCars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDetails, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAllManufacturers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnDetails)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExpMaintenanceCert)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btnFirstCarAvailable)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvailabilityOfCars)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAllManufacturers)
                            .addComponent(jLabel7)
                            .addComponent(srchSerialNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSrchSerialNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(search1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(search2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch2Filter)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap(427, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
         int selectedRow =carJTable.getSelectedRow();
        if(selectedRow<0){
        JOptionPane.showMessageDialog(null, "Please select any row!");
        
        }
        else{
        Car account=(Car) carJTable.getValueAt(selectedRow,0);
        ViewCarJPanel panel= new ViewCarJPanel(userProcessContainer,account);
         userProcessContainer.add("ViewAccountJPanel",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void searchDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDropDownActionPerformed
        // TODO add your handling code here:
    
                   
                
    }//GEN-LAST:event_searchDropDownActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int count;
        if (searchDropDown.getSelectedItem()=="Make")
        { 
           searchByMake();
           count= carJTable.getRowCount();
           if(count==0)
           {
           JOptionPane.showMessageDialog(null, "No such record found");
           }
        }
        else if (searchDropDown.getSelectedItem()=="Serial Number"){
         
             searchbySerialNumber();
             count= carJTable.getRowCount();
             if(count==0)
           {
           JOptionPane.showMessageDialog(null, "No such record found");
           }
        
        }
        else if (searchDropDown.getSelectedItem()=="Model Number"){
        searchByModelNo();
        count= carJTable.getRowCount();
           if(count==0)
           {
           JOptionPane.showMessageDialog(null, "No such record found");
           }
        }
        else if(searchDropDown.getSelectedItem()=="City"){
        
        searchByCity();
        count= carJTable.getRowCount();
           if(count==0)
           {
           JOptionPane.showMessageDialog(null, "No such record found");
           }
        }
        
        else if(searchDropDown.getSelectedItem()=="Manufactured Year"){
        
        searchByYear();
        count= carJTable.getRowCount();
           if(count==0)
           {
           JOptionPane.showMessageDialog(null, "No such record found");
           }
        }
        else
             JOptionPane.showMessageDialog(null, "Please select item from dropdown");
            
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExpMaintenanceCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpMaintenanceCertActionPerformed
        // TODO add your handling code here:
        ExpMaintenanceCertificateJPanel panel= new  ExpMaintenanceCertificateJPanel(userProcessContainer,carList);
        userProcessContainer.add(" ExpMaintenanceCertJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
        
    }//GEN-LAST:event_btnExpMaintenanceCertActionPerformed

    private void btnFirstCarAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstCarAvailableActionPerformed
        // TODO add your handling code here:
       FirstCarJPanel panel= new  FirstCarJPanel(userProcessContainer,carList);
        userProcessContainer.add("FirstCarJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnFirstCarAvailableActionPerformed

    private void btnAvailabilityOfCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailabilityOfCarsActionPerformed
        // TODO add your handling code here:
        
       AvailabilityOfCarsJPanel panel= new  AvailabilityOfCarsJPanel(userProcessContainer,carList);
        userProcessContainer.add("AvailabilityOfCarsJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAvailabilityOfCarsActionPerformed

    private void btnAllManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllManufacturersActionPerformed
        // TODO add your handling code here:
        
        ManufacturerJPanel panel= new  ManufacturerJPanel(userProcessContainer,carList);
        userProcessContainer.add("ManufacturerJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
        
    }//GEN-LAST:event_btnAllManufacturersActionPerformed

    private void search1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1TextFieldActionPerformed

    private void btnSearch2FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2FilterActionPerformed
        // TODO add your handling code here:
        String search1=  search1TextField.getText();
        String search2=  search2TextField.getText();
        TwoFilterJPanel panel= new  TwoFilterJPanel(userProcessContainer,carList,search1,search2 );
        userProcessContainer.add("TwoFilterJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearch2FilterActionPerformed

    private void btnSrchSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchSerialNumberActionPerformed
        // TODO add your handling code here:
        
        
        String serialNo= srchSerialNoJTextField.getText();

        DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel();

        dtm.setRowCount(0);
   if(serialNo.length()==0)
       JOptionPane.showMessageDialog(null, "Please enter the serial number");
       
        for(Car car: carList.getCarList())
        {  Object[] row=new Object[6];
            if(Integer.parseInt(serialNo)==car.getSerialNo())

            {

                row[0]=car;
                row[1]=car.getSerialNo();
                row[2]=car.getModelNo();
                row[3]=car.getAvailableCity();
                row[4]=car.getDistance();
                row[5]=car.getManufacturedYear();

                dtm.addRow(row);
            }
        }
        if(carJTable.getRowCount()==0)
        JOptionPane.showMessageDialog(null, "No such record found!");

    }//GEN-LAST:event_btnSrchSerialNumberActionPerformed
  private void searchByMake()
   {  // CarDirectory tempList1;
      String make= searchTextField.getText();
      DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel(); 
   final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dtm);
    carJTable.setRowSorter(sorter);
    if (make.length() == 0) {
        JOptionPane.showMessageDialog(null, "Please enter the text field!");
          sorter.setRowFilter(null);
           
        } else
        {
        sorter.setRowFilter(RowFilter.regexFilter(make));
          
    }
   
 
       


}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllManufacturers;
    private javax.swing.JButton btnAvailabilityOfCars;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnExpMaintenanceCert;
    private javax.swing.JButton btnFirstCarAvailable;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2Filter;
    private javax.swing.JButton btnSrchSerialNumber;
    private javax.swing.JTable carJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search1TextField;
    private javax.swing.JTextField search2TextField;
    private javax.swing.JComboBox<String> searchDropDown;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField srchSerialNoJTextField;
    // End of variables declaration//GEN-END:variables

    private void searchbySerialNumber() {
        String serialNumber= searchTextField.getText();
      DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel(); 
   final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dtm);
    carJTable.setRowSorter(sorter);
    if (serialNumber.length() == 0) {
 JOptionPane.showMessageDialog(null, "Please enter the text field!");
          sorter.setRowFilter(null);
          
        } else {
          sorter.setRowFilter(RowFilter.regexFilter(serialNumber));
    }
    }

    private void searchByModelNo() {
         String ModelNumber= searchTextField.getText();
      DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel(); 
   final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dtm);
    carJTable.setRowSorter(sorter);
    if (ModelNumber.length() == 0) {
         JOptionPane.showMessageDialog(null, "Please enter the text field!");
          sorter.setRowFilter(null);
          
        } else {
          sorter.setRowFilter(RowFilter.regexFilter(ModelNumber));
    }
      
    }

    private void searchByCity() {
        String city= searchTextField.getText();
      DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel(); 
   final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dtm);
    carJTable.setRowSorter(sorter);
    if (city.length() == 0) {
          JOptionPane.showMessageDialog(null, "Please enter the text field!");
          sorter.setRowFilter(null);
          
        } else {
          sorter.setRowFilter(RowFilter.regexFilter(city));
    }
    }

    private void searchByYear() {
         String year= searchTextField.getText();
      DefaultTableModel dtm = (DefaultTableModel) carJTable.getModel(); 
   final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dtm);
    carJTable.setRowSorter(sorter);
    if (year.length() == 0) {
         JOptionPane.showMessageDialog(null, "Please enter the text field!");
          sorter.setRowFilter(null);
          
        } else {
          sorter.setRowFilter(RowFilter.regexFilter(year));
    }
    }
}
