/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarDirectory;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author devinajaiswal
 */
public class ViewCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCarJPanel
     */
    private JPanel userProcessContainer;
    private Car car;
    ViewCarJPanel(JPanel userProcessContainer,Car account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.car=account;
        populateAccountDetails();
//        btnSave.setEnabled(false);
//        btnUpdate.setEnabled(true);
        
    }

    private void populateAccountDetails(){
    makeTextField.setText((car.getMake()));
    modelNoTextField.setText(car.getModelNo());
    cityTextField.setText(car.getAvailableCity());
    manufacturedYearTextField.setText(Integer.toString(car.getManufacturedYear()));
    minSeatsTextField.setText(Integer.toString(car.getMinSeats()));
   maxSeatsTextField.setText(Integer.toString(car.getMaxSeats()));
    distanceTextField.setText(Double.toString(car.getDistance()));
    serialNoTextField.setText(Integer.toString(car.getSerialNo()));
    maintenanceCertificateCheckBox.setSelected(car.isMaintenanceCertificate());
       availabilityOfCarCheckBox.setSelected(car.isAvailablityOfCar());
       
 //System.out.print(car.isMaintenanceCertificate());
    
    
     
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        makeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        manufacturedYearTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        minSeatsTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maxSeatsTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        serialNoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modelNoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        distanceTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        maintenanceCertificateCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        availabilityOfCarCheckBox = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        headerJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        headerJLabel.setForeground(new java.awt.Color(153, 0, 0));
        headerJLabel.setText("View Car Details");

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Make");

        makeTextField.setEnabled(false);
        makeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Manufactured Year");

        manufacturedYearTextField.setEnabled(false);

        jLabel3.setText("Minimum seats");

        minSeatsTextField.setEnabled(false);

        jLabel4.setText("Maximum seats");

        maxSeatsTextField.setEnabled(false);

        jLabel5.setText("Serial Number");

        serialNoTextField.setEnabled(false);

        jLabel7.setText("Model Number");

        modelNoTextField.setEnabled(false);

        jLabel6.setText("City");

        cityTextField.setEnabled(false);
        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Distance");

        distanceTextField.setEnabled(false);

        jLabel8.setText("Maintenance Certificate ");

        maintenanceCertificateCheckBox.setEnabled(false);
        maintenanceCertificateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceCertificateCheckBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Availability of Car");

        availabilityOfCarCheckBox.setEnabled(false);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(258, 258, 258)
                        .addComponent(headerJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maxSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manufacturedYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(serialNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modelNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maintenanceCertificateCheckBox)
                                    .addComponent(distanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availabilityOfCarCheckBox))))))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnSave)
                .addGap(46, 46, 46)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addComponent(btnBack)
                                                                .addGap(28, 28, 28)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel1)
                                                                    .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel2)
                                                                    .addComponent(manufacturedYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(headerJLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(minSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel4))
                                                    .addComponent(maxSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5))
                                            .addComponent(serialNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(modelNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(distanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(maintenanceCertificateCheckBox))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(availabilityOfCarCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(426, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void makeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeTextFieldActionPerformed

    private void maintenanceCertificateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceCertificateCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceCertificateCheckBoxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
  if (makeTextField.getText().length()==0)
                  JOptionPane.showMessageDialog(null, "Please enter the make of car!");
      if (modelNoTextField.getText().length()==0)
                  JOptionPane.showMessageDialog(null, "Please enter the Model Number of car!"); 
      if (cityTextField.getText().length()==0)
                  JOptionPane.showMessageDialog(null, "Please enter the city!");
     
       try{makeTextField.getText();}
       catch(NullPointerException e)
       
       {
          JOptionPane.showMessageDialog(null, "Please enter the make!");
       }
       
        try{
       Double.parseDouble(distanceTextField.getText());
         }
        catch(NumberFormatException e)
         {
         
        JOptionPane.showMessageDialog(null, "Please enter number for distance!");
         
         }
         try{
         
         Integer.parseInt(manufacturedYearTextField.getText());
         
         }
         catch(NumberFormatException e)
         {
         
        JOptionPane.showMessageDialog(null, "Please enter number for manufactured year!");
         
         }
         try{
         
    Integer.parseInt(minSeatsTextField.getText());
                 
         }
         catch(NumberFormatException e)
         {
         
        JOptionPane.showMessageDialog(null, "Please enter number for minimum seat!");
         
         }
          try{
         
             Integer.parseInt(maxSeatsTextField.getText());
   
         }
         catch(NumberFormatException e)
         {
         
        JOptionPane.showMessageDialog(null, "Please enter number for maximum seat!");
         
         }
       
      try{
         
            Integer.parseInt(serialNoTextField.getText());
                   
         }
         catch(NumberFormatException e)
         {
         
        JOptionPane.showMessageDialog(null, "Please enter number for serial number!");
         
         }

         car.setMake(makeTextField.getText());
         car.setModelNo(modelNoTextField.getText());
         car.setManufacturedYear(Integer.parseInt(manufacturedYearTextField.getText()));
         car.setAvailableCity(cityTextField.getText());
        car.setAvailablityOfCar(availabilityOfCarCheckBox.isEnabled());
        car.setDistance(Double.parseDouble(distanceTextField.getText()));
        //System.out.println(distanceTextField.getText());
       
        car.setMaintenanceCertificate(maintenanceCertificateCheckBox.isEnabled());
        car.setMaxSeats(Integer.parseInt(maxSeatsTextField.getText()));
        car.setMinSeats(Integer.parseInt(minSeatsTextField.getText()));
     
        car.setSerialNo(Integer.parseInt(serialNoTextField.getText()));
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Car updated successfully!");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        CarDirectory.updatedOn= new Date();
         makeTextField.setEnabled(true);
        manufacturedYearTextField.setEnabled(true);
        minSeatsTextField.setEnabled(true);
        maxSeatsTextField.setEnabled(true);
        serialNoTextField.setEnabled(true);
        modelNoTextField.setEnabled(true);
        cityTextField.setEnabled(true);
         distanceTextField.setEnabled(true);
         maintenanceCertificateCheckBox.setEnabled(true);
         availabilityOfCarCheckBox.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox availabilityOfCarCheckBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField distanceTextField;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox maintenanceCertificateCheckBox;
    private javax.swing.JTextField makeTextField;
    private javax.swing.JTextField manufacturedYearTextField;
    private javax.swing.JTextField maxSeatsTextField;
    private javax.swing.JTextField minSeatsTextField;
    private javax.swing.JTextField modelNoTextField;
    private javax.swing.JTextField serialNoTextField;
    // End of variables declaration//GEN-END:variables
}
